AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/**/*
    - 'vendor/**/*'
    - config/environments/**/*
    - config/initializers/**/*
    - config/application.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - bin/*

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/AsciiComments:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/FormatString:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30
